/** Declaration file generated by dts-gen */

export function dotPath(a0: any, a1: any, ...args: any[]): any;

export function endsWith(a0: any, a1: any, ...args: any[]): any;

export function eqLength(a: any, b: any, ...args: any[]): any;

export function findByProp(a0: any, a1: any, a2: any, ...args: any[]): any;

export function findIndexByProp(a0: any, a1: any, a2: any, ...args: any[]): any;

export function isNilOrEmpty(a: any, ...args: any[]): any;

export function isNotNil(a: any, ...args: any[]): any;

export function isNotWithin(a0: any, a1: any, a2: any, ...args: any[]): any;

export function isUndefined(r: any): any;

export function isWithin(a0: any, a1: any, a2: any, ...args: any[]): any;

export function log(r: any): any;

export function mapKeys(a0: any, a1: any, ...args: any[]): any;

export function random(r: any, e: any): any;

export function rangeStep(a0: any, a1: any, a2: any, ...args: any[]): any;

export function sample(r: any): any;

export function startsWith(a0: any, a1: any, ...args: any[]): any;

export function toDate(r: any): any;

export function toNumber(a0: any, ...args: any[]): any;

export function trace(a0: any, a1: any, ...args: any[]): any;

export namespace dotPath {
    const prototype: {
    };

}

export namespace endsWith {
    const prototype: {
    };

}

export namespace eqLength {
    const prototype: {
    };

}

export namespace findByProp {
    const prototype: {
    };

}

export namespace findIndexByProp {
    const prototype: {
    };

}

export namespace isNilOrEmpty {
    const prototype: {
    };

}

export namespace isNotNil {
    const prototype: {
    };

}

export namespace isNotWithin {
    const prototype: {
    };

}

export namespace isUndefined {
    const prototype: {
    };

}

export namespace isWithin {
    const prototype: {
    };

}

export namespace log {
    const prototype: {
    };

}

export namespace mapKeys {
    const prototype: {
    };

}

export namespace random {
    const prototype: {
    };

}

export namespace rangeStep {
    const prototype: {
    };

}

export namespace sample {
    const prototype: {
    };

}

export namespace startsWith {
    const prototype: {
    };

}

export namespace toDate {
    const prototype: {
    };

}

export namespace toNumber {
    const prototype: {
    };

}

export namespace trace {
    const prototype: {
    };

}

